// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/listen-fix/DiagnosticDashboard.tsx": () => import("../components/mockups/listen-fix/DiagnosticDashboard.tsx"),
  "./components/mockups/listen-fix/LandingPage.tsx": () => import("../components/mockups/listen-fix/LandingPage.tsx")
};
